app:
  timezone: Europe/Moscow
  auth:
    header-name: Authorization
    access-token-response-header: X-Access-Token
    header-prefix: Bearer
    jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-name: accessToken
    refresh-token-name: refreshToken
    access-token-expiration: 15m
    refresh-token-expiration: 30d
    refresh-token-path: /api
    secure: true
    same-site: Strict

spring:
  application:
    name: sobestime
    version: @project.version@
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: false